const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Dozhdevik:D}=require('../bestiary/dozhdevik/animations/dozhdevik.js');
const html=fs.readFileSync('tower-defense.html','utf8'),slice=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
function setup(){const G={t:12,gold:0,fx:[],foes:[],paths:[{}],spawnIdx:0};const c=vm.createContext({G,Math,Ugolek:{},Dozhdevik:D,save:{seen:{}},foePos:f=>({x:f.d,y:1}),foeHeading:()=>.3,parts:()=>[],flash(){},sndKill(){},sndFoe(){},writeSave(){},showHint(){}});vm.runInContext(slice('function eyes(','/* Карточка — публичный договор'),c);vm.runInContext(slice('function dmgFoe(','function towerStats('),c);vm.runInContext(slice('function spawn(type,','const SIEGE_SLOTS'),c);return {G,c}}
test('death spawns exactly four live spores once with the same path, scale and birth time',()=>{const {G,c}=setup(),f=c.spawn('puffball',2,{pi:0,d:3});c.dmgFoe(f,1000,'ball');const spores=G.foes.filter(f=>f.type==='spore');assert.equal(spores.length,4);for(let i=0;i<4;i++){assert.equal(spores[i].hp,16);assert.equal(spores[i].scale,2);assert.equal(spores[i].pi,0);assert.equal(spores[i].d,3-.35-i*.12);assert.equal(spores[i].bornAt,12);assert.equal(spores[i].hidden,false)}assert.equal(G.gold,16);assert.equal(G.fx.filter(e=>e.kind==='puffballBurst').length,1);c.dmgFoe(f,1000,'chain');assert.equal(G.foes.length,5);assert.equal(G.gold,16);assert.ok(G.foes.some(f=>!f.dead));});
test('gate death stays on path; newborn spores can be killed immediately without recursive splitting',()=>{const {G,c}=setup(),f=c.spawn('puffball',1,{pi:0,d:0});f.siege=true;c.dmgFoe(f,100,'splash');const spores=G.foes.filter(f=>f.type==='spore');assert.equal(spores.length,4);for(const s of spores){assert.equal(s.d,0);assert.equal(s.siege,false);c.dmgFoe(s,100,'splash')}assert.equal(G.gold,24);assert.equal(G.foes.length,5);assert.ok(G.foes.every(f=>f.dead))});
test('attack has a unique contact and returns to rest; walk depends on distance',()=>{assert.equal(D.attackProgress(0),D.CONTACT);assert.equal(D.pose({state:'attack',attack:D.CONTACT}).jet,1);assert.equal(D.pose({state:'attack',attack:1}).jet,0);assert.equal(D.attackProgress(1.8),null);assert.deepEqual(D.pose({state:'walk',distance:2,time:1}),D.pose({state:'walk',distance:2,time:10}))});
test('all life cycle drawings are finite, pure and keep canvas balanced',()=>{let depth=0;const c=new Proxy({},{set(o,k,v){o[k]=v;return true},get(o,k){if(k==='save')return()=>depth++;if(k==='restore')return()=>depth--;if(k.startsWith('create'))return()=>({addColorStop(){}});return o[k]||((...args)=>{for(const v of args)if(typeof v==='number')assert.ok(Number.isFinite(v),k)})}});for(let i=0;i<8;i++)for(const p of [0,.25,.58,.8,1]){const o=Object.freeze({size:24,heading:i*Math.PI/4,state:'attack',attack:p,progress:p,birth:p,target:Object.freeze({x:50,y:10})});D.draw(c,o);D.drawSpore(c,o);D.drawDeath(c,o);assert.equal(depth,0)}});
test('spore matures at eight simulation seconds, preserving damage ratio, path and slow without reward',()=>{const {G,c}=setup(),f=c.spawn('spore',2,{pi:0,d:3});f.hp=8;f.slow=.45;f.slowT=4;c.updateSporeGrowth(f,6);assert.equal(f.type,'spore');c.updateSporeGrowth(f,1);assert.ok(f.r>.16&&f.r<.34);c.updateSporeGrowth(f,1);assert.equal(f.type,'puffball');assert.equal(f.hpMax,120);assert.equal(f.hp,60);assert.equal(f.pi,0);assert.equal(f.d,3);assert.equal(f.slow,.45);assert.equal(f.slowT,4);assert.equal(G.gold,0);assert.equal(G.foes.length,1);assert.equal(f.sp,1);assert.equal(f.r,.34)});
test('matured spores preserve siege but never start another generation',()=>{
  const {G,c}=setup(),parent=c.spawn('puffball',1,{pi:0,d:1});
  c.dmgFoe(parent,1000,'ball');
  const children=G.foes.filter(f=>f.type==='spore');assert.equal(children.length,4);
  const child=children[0];child.siege=true;child.slot=3;child.atk=.01;
  for(const f of children){c.updateSporeGrowth(f,7.99);assert.equal(f.type,'spore');c.updateSporeGrowth(f,20);assert.equal(f.type,'puffball');}
  assert.equal(child.siege,true);assert.equal(child.slot,3);assert.equal(child.atk,1.8);
  for(const f of children)c.dmgFoe(f,1000,'ball');
  assert.equal(G.foes.length,5);assert.ok(G.foes.every(f=>f.dead));assert.equal(G.gold,80);
  const dead=c.spawn('spore',1,{pi:0,d:1});dead.dead=true;c.updateSporeGrowth(dead,20);assert.equal(dead.type,'spore');
});
test('spore lunge reaches contact and settles; growing and attacking render safely',()=>{assert.equal(D.sporeAttackProgress(0),.5);assert.equal(D.sporePose({state:'attack',attack:.5}).dart,1);assert.equal(D.sporePose({state:'attack',attack:1}).dart,0);let depth=0;const c=new Proxy({},{set(o,k,v){o[k]=v;return true},get(o,k){if(k==='save')return()=>depth++;if(k==='restore')return()=>depth--;if(k.startsWith('create'))return()=>({addColorStop(){}});return o[k]||(()=>{})}});for(const growth of [0,.2,.5,.99,1]){D.drawSpore(c,Object.freeze({size:40,growth,state:'attack',attack:.5,target:Object.freeze({x:60,y:0})}));assert.equal(depth,0)}});
