const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Dreven:D}=require('../bestiary/dreven/animations/dreven.js');
const html=fs.readFileSync('tower-defense.html','utf8'),slice=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
function setup(){const G={t:0,gold:0,fx:[],foes:[]};const c=vm.createContext({G,Math,Ugolek:{},Dreven:D,foePos:f=>f.pos,parts:()=>[],flash(){},sndKill(){}});vm.runInContext(slice('function eyes(','/* Карточка — публичный договор'),c);vm.runInContext(slice('function dmgFoe(','function towerStats('),c);const f={type:'golem',hp:260,armor:9,buff:{armor:0},pos:{x:0,y:0},bounty:30};G.foes.push(f);return {c,f,G}}
test('lightning multiplies before armor, then burns exactly 5 health regardless of tick size',()=>{for(const dt of [.016,.1,1,4]){const {c,f}=setup();assert.equal(c.dmgFoe(f,8,'chain'),5);for(let t=0;t<3;t+=dt)c.updateSmoulder(f,dt);assert.ok(Math.abs(f.hp-250)<1e-8);assert.equal(f.smoulder,0)}});
test('other damage does not ignite; refresh does not stack burn; burn ignores armor and siege bonus',()=>{const {c,f}=setup();assert.equal(c.dmgFoe(f,13,'ball'),4);assert.equal(f.smoulder,undefined);c.dmgFoe(f,8,'chain');c.updateSmoulder(f,1);c.dmgFoe(f,8,'chain');assert.equal(f.smoulder,2.5);f.siege=true;f.armor=100;const hp=f.hp;c.updateSmoulder(f,3);assert.equal(hp-f.hp,5)});
test('burn death grants bounty only once and no later hit can pay again',()=>{const {c,f,G}=setup();c.dmgFoe(f,8,'chain');f.hp=1;c.updateSmoulder(f,1);assert.equal(f.dead,true);assert.equal(G.gold,30);c.updateSmoulder(f,2);assert.equal(c.dmgFoe(f,9,'chain'),0);assert.equal(G.gold,30)});
test('six roots retain support; strike reaches contact and returns; idle pose is stable',()=>{for(let i=0;i<120;i++){const p=D.pose({state:'walk',distance:i/100});assert.equal(p.roots.length,6);assert.ok(p.roots.filter(r=>r.lift>1e-8).length<=1)}assert.equal(D.pose({state:'attack',attack:D.CONTACT}).reach,1);assert.equal(D.pose({state:'attack',attack:1}).reach,0);assert.equal(D.attackProgress(0),D.CONTACT);assert.equal(D.attackProgress(2),null);assert.deepEqual(D.pose({state:'idle',time:1}),D.pose({state:'idle',time:5}))});
test('volume projection is finite at all headings and attack phases, with balanced canvas state',()=>{
 let depth=0;const c=new Proxy({},{set(o,k,v){o[k]=v;return true},get(o,k){if(k==='save')return()=>depth++;if(k==='restore')return()=>depth--;if(k.startsWith('create'))return()=>({addColorStop(){}});return o[k]||((...args)=>{for(const v of args)if(typeof v==='number')assert.ok(Number.isFinite(v),k)})}});
 for(let i=0;i<8;i++)for(const a of [0,.3,.6,.8,1]){D.draw(c,Object.freeze({viewHeading:i*Math.PI/4,state:'attack',attack:a,size:24,burning:1,target:Object.freeze({x:30,y:10})}));assert.equal(depth,0)}
});
