(()=>{'use strict';const D=ArsenalCurrent.TeslaDesign,roman=['I','II','III','IV','V'],desc=['Компактная открытая катушка: три толстых витка.','Широкое кольцо вокруг верхнего электрода.','Два низких электрода на наклонных стойках.','Высокие боковые катушки и бронированный корпус.','Открытая верхняя вилка и мощный центральный электрод.'];
document.querySelector('#ranks').innerHTML=D.names.map((n,i)=>`<article><span class="label">${roman[i]} / ${i===4?'Максимум':'Уровень '+(i+1)}</span><canvas data-rank="${i+1}" role="img" aria-label="${n}, уровень ${i+1}"></canvas><h3>${n}</h3><p>${desc[i]}</p></article>`).join('');document.querySelector('#mini').innerHTML=D.names.map((n,i)=>`<figure><canvas data-rank="${i+1}" data-size="40" role="img" aria-label="${n} в игровом размере"></canvas><figcaption>${roman[i]}</figcaption></figure>`).join('');
let sil=false,level=1,shot=-10000;const reduced=matchMedia('(prefers-reduced-motion: reduce)');document.querySelector('#sil').onchange=e=>sil=e.target.checked;document.querySelector('#fire').onclick=()=>shot=performance.now();const status=()=>document.querySelector('#status').textContent=`${D.names[level-1]} · цепь до ${ArsenalCurrent.TOWER_TIERS.tesla.chain[level-1]} целей`;document.querySelector('#level').onchange=e=>{level=+e.target.value;shot=-10000;status()};status();
function context(el){const w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio||1,2);if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d)}const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);return {c,w,h};}
const els=[...document.querySelectorAll('[data-rank]')],battle=document.querySelector('#battle');let last=0;
function frame(ms){requestAnimationFrame(frame);if(document.hidden||ms-last<32)return;last=ms;const age=(ms-shot)/1000,flash=age>=0&&age<.14&&!reduced.matches?.14-age:0,cool=age<1?1-age:0;
for(const el of els){const {c,w,h}=context(el),size=+el.dataset.size||Math.min(w,h)*.84;c.save();c.translate(w/2,h*.62);D.body(c,size,+el.dataset.rank,sil);if(!sil)D.live(c,size,{lvl:+el.dataset.rank,flash,cool},reduced.matches?0:ms/1000);c.restore();}
const {c,w,h}=context(battle),origin=[w*.17,h*.52],targets=[[w*.47,h*.34],[w*.67,h*.24],[w*.82,h*.45],[w*.64,h*.7],[w*.43,h*.76]],count=ArsenalCurrent.TOWER_TIERS.tesla.chain[level-1];c.save();c.translate(...origin);D.body(c,Math.min(100,w*.25),level);D.live(c,Math.min(100,w*.25),{lvl:level,flash,cool},reduced.matches?0:ms/1000);c.restore();const active=age>=0&&age<(reduced.matches?.8:.28);
for(let i=0;i<targets.length;i++){const [x,y]=targets[i];c.fillStyle=active&&i<count?'#e6e9ad':'#657959';c.beginPath();c.arc(x,y,10,0,7);c.fill();}
if(active){let from=[origin[0],origin[1]+D.crownY(level)*Math.min(100,w*.25)];for(const to of targets.slice(0,count)){const dx=to[0]-from[0],dy=to[1]-from[1],len=Math.hypot(dx,dy),nx=-dy/len,ny=dx/len;c.beginPath();c.moveTo(...from);for(let j=1;j<6;j++){const offset=j%2?5:-5;c.lineTo(from[0]+dx*j/6+nx*offset,from[1]+dy*j/6+ny*offset)}c.lineTo(...to);c.strokeStyle='#cdd77f';c.lineWidth=4;c.stroke();c.strokeStyle='#fffadc';c.lineWidth=1.5;c.stroke();from=to;}}
}requestAnimationFrame(frame);})();
