(()=>{'use strict';const D=ArsenalCurrent.FrostDesign,roman=['I','II','III','IV','V'],desc=['Один кристалл в каменной чаше.','Добавляются два маленьких боковых осколка.','Та же боковая пара вырастает; чаша получает обод.','Позади появляются ещё два кристалла. Все прежние сохранены.','Пять кристаллов и внешний ледяной венец.'];
document.querySelector('#ranks').innerHTML=D.names.map((n,i)=>`<article><span class="label">${roman[i]} / ${i===4?'Максимум':'Уровень '+(i+1)}</span><canvas data-rank="${i+1}" role="img" aria-label="${n}, уровень ${i+1}"></canvas><h3>${n}</h3><p>${desc[i]}</p></article>`).join('');document.querySelector('#mini').innerHTML=D.names.map((n,i)=>`<figure><canvas data-rank="${i+1}" data-size="40" role="img" aria-label="${n} в игровом размере"></canvas><figcaption>${roman[i]}</figcaption></figure>`).join('');
let sil=false,level=1,shot=-10000,phase=0,last=0,wasSlowed=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)'),stats=()=>ArsenalCurrent.towerStats({type:'frost',lvl:level});function status(slow=false){const st=stats();document.querySelector('#status').textContent=`${D.names[level-1]} · урон ${+st.dmg.toFixed(2)} · замедление ${Math.round(st.slow*100)}% на ${st.slowT} с · ${slow?'мишень замедлена':'обычная скорость'}`;}document.querySelector('#sil').onchange=e=>sil=e.target.checked;document.querySelector('#fire').onclick=()=>{shot=performance.now()};document.querySelector('#level').onchange=e=>{level=+e.target.value;shot=-10000;status()};status();
function context(el){const w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio||1,2);if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d)}const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);return {c,w,h};}const els=[...document.querySelectorAll('[data-rank]')],battle=document.querySelector('#battle');
function frame(ms){requestAnimationFrame(frame);if(document.hidden||ms-last<32)return;const dt=Math.min((ms-last)/1000,.1);last=ms;const age=(ms-shot)/1000,travel=reduced.matches?0:.4,slow=age>=travel&&age<travel+stats().slowT,flash=reduced.matches?0:Math.max(0,.07-age);if(slow!==wasSlowed){wasSlowed=slow;status(slow);}if(!reduced.matches)phase+=dt*(slow?1-stats().slow:1)*.65;
for(const el of els){const {c,w,h}=context(el),s=+el.dataset.size||Math.min(w,h)*.84;c.save();c.translate(w/2,h*.62);D.body(c,s,+el.dataset.rank,sil);if(!sil)D.live(c,s,{lvl:+el.dataset.rank,flash},reduced.matches?0:ms/1000);c.restore();}
const {c,w,h}=context(battle),s=Math.min(95,w*.26),origin=[w*.18,h*.65],target=[w*(.68+.15*Math.sin(phase)),h*.64];c.save();c.translate(...origin);D.body(c,s,level);D.live(c,s,{lvl:level,flash},reduced.matches?0:ms/1000);c.restore();c.strokeStyle='#78906b';c.lineWidth=2;c.beginPath();c.moveTo(w*.5,h*.7);c.lineTo(w*.9,h*.7);c.stroke();c.fillStyle=slow?'#a7e2d2':'#a1ac77';c.beginPath();c.arc(...target,11,0,7);c.fill();
if(age>=0&&age<travel&&!reduced.matches){const t=age/travel,start=[origin[0],origin[1]-D.height(level)*.47*s],x=start[0]+(target[0]-start[0])*t,y=start[1]+(target[1]-start[1])*t;c.fillStyle='#dcfff0';c.beginPath();c.moveTo(x+8,y);c.lineTo(x,y-4);c.lineTo(x-8,y);c.lineTo(x,y+4);c.closePath();c.fill();}
if(slow){c.strokeStyle='#d9fff0';c.lineWidth=1.5;for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.moveTo(target[0]+Math.cos(a)*14,target[1]+Math.sin(a)*14);c.lineTo(target[0]+Math.cos(a)*20,target[1]+Math.sin(a)*20);c.stroke();}}
}requestAnimationFrame(frame);})();
