(()=>{'use strict';const D=ArsenalCurrent.MortarDesign,roman=['I','II','III','IV','V'],desc=['Открытая компактная люлька.','Две угловатые боковые опоры.','Броня между теми же боковыми опорами.','Усиленные боковые опоры и четыре упора.','Расширенная рама; боковые опоры сохранены и усилены.'];
document.querySelector('#ranks').innerHTML=D.names.map((n,i)=>`<article><span class="label">${roman[i]} / ${i===4?'Максимум':'Уровень '+(i+1)}</span><canvas data-rank="${i+1}" role="img" aria-label="${n}, уровень ${i+1}"></canvas><h3>${n}</h3><p>${desc[i]}</p></article>`).join('');document.querySelector('#mini').innerHTML=D.names.map((n,i)=>`<figure><canvas data-rank="${i+1}" data-size="40" role="img" aria-label="${n} в игровом размере"></canvas><figcaption>${roman[i]}</figcaption></figure>`).join('');
let aim=-35*Math.PI/180,sil=false,level=1,shot=-10000;const reduced=matchMedia('(prefers-reduced-motion: reduce)');document.querySelector('#angle').oninput=e=>aim=+e.target.value*Math.PI/180;document.querySelector('#sil').onchange=e=>sil=e.target.checked;document.querySelector('#fire').onclick=()=>shot=performance.now();function status(){const st=ArsenalCurrent.towerStats({type:'mortar',lvl:level});document.querySelector('#status').textContent=`${D.names[level-1]} · урон ${+st.dmg.toFixed(2)} · ${st.rate} выстр./с · радиус взрыва ${st.splash} клетки`;}document.querySelector('#level').onchange=e=>{level=+e.target.value;shot=-10000;status()};status();
function ctx(el){const w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio||1,2);if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d)}const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);return {c,w,h};}
const els=[...document.querySelectorAll('[data-rank]')],battle=document.querySelector('#battle');let last=0;
function frame(ms){requestAnimationFrame(frame);if(document.hidden||ms-last<32)return;last=ms;const age=(ms-shot)/1000,flash=!reduced.matches?Math.max(0,.07-age):0,recoil=!reduced.matches?Math.max(0,1-age/.35):0;
for(const el of els){const {c,w,h}=ctx(el),s=+el.dataset.size||Math.min(w,h)*.82;c.save();c.translate(w/2,h/2);D.body(c,s,+el.dataset.rank,sil);D.live(c,s,{lvl:+el.dataset.rank,aim,recoil,flash},sil);c.restore();}
const {c,w,h}=ctx(battle),s=Math.min(80,w*.21),origin=[w*.17,h*.7],target=[w*.76,h*.7],radius=ArsenalCurrent.towerStats({type:'mortar',lvl:level}).splash*26;
c.save();c.translate(...origin);D.body(c,s,level);D.live(c,s,{lvl:level,aim:0,recoil,flash});c.restore();
for(const [dx,dy]of [[0,0],[-22,-14],[25,10]]){c.fillStyle='#8a9670';c.beginPath();c.arc(target[0]+dx,target[1]+dy,7,0,7);c.fill();}
if(!reduced.matches&&age>=0&&age<.95){const t=age/.95,start=origin[0]+D.muzzle(level)*s,x=start+(target[0]-start)*t,y=origin[1]-Math.sin(t*Math.PI)*h*.43;c.fillStyle='#132a2180';c.beginPath();c.ellipse(x,origin[1]+8,7,3,0,0,7);c.fill();c.fillStyle='#d4c193';c.beginPath();c.arc(x,y,5,0,7);c.fill();}
const impact=reduced.matches?age:age-.95;if(impact>=0&&impact<.65){const p=impact/.65;c.strokeStyle=`rgba(233,178,103,${1-p})`;c.lineWidth=3;c.beginPath();c.ellipse(...target,radius*(.3+p*.7),radius*.52*(.3+p*.7),0,0,7);c.stroke();c.fillStyle=`rgba(242,211,148,${(1-p)*.6})`;c.beginPath();c.arc(...target,12*(1-p),0,7);c.fill();}}
requestAnimationFrame(frame);})();
